/*
 * Recommendation API
 *
 * This is a recommendation API using k-means Clustering
 *
 * API version: 1.0.0
 * Contact: capela.nuno@ua.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

type Item struct {

	// Identifier of the item
	Id string `json:"id"`

	//Which centroid is it nearest to
	BelongsTo int `json:"belongsTo,omitempty"`

	// Data of the item
	Data string `json:"data"`
}

type Items []Item
