# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CinemaItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, location: str=None):  # noqa: E501
        """CinemaItem - a model defined in Swagger

        :param id: The id of this CinemaItem.  # noqa: E501
        :type id: str
        :param name: The name of this CinemaItem.  # noqa: E501
        :type name: str
        :param location: The location of this CinemaItem.  # noqa: E501
        :type location: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'location': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'location': 'location'
        }

        self._id = id
        self._name = name
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'CinemaItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CinemaItem of this CinemaItem.  # noqa: E501
        :rtype: CinemaItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CinemaItem.


        :return: The id of this CinemaItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CinemaItem.


        :param id: The id of this CinemaItem.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this CinemaItem.


        :return: The name of this CinemaItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CinemaItem.


        :param name: The name of this CinemaItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def location(self) -> str:
        """Gets the location of this CinemaItem.


        :return: The location of this CinemaItem.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this CinemaItem.


        :param location: The location of this CinemaItem.
        :type location: str
        """

        self._location = location
