# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Item(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, data: str=None):  # noqa: E501
        """Item - a model defined in Swagger

        :param id: The id of this Item.  # noqa: E501
        :type id: str
        :param data: The data of this Item.  # noqa: E501
        :type data: str
        """
        self.swagger_types = {
            'id': str,
            'data': str
        }

        self.attribute_map = {
            'id': 'id',
            'data': 'data'
        }

        self._id = id
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Item':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Item of this Item.  # noqa: E501
        :rtype: Item
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Item.

        Identifier of the movie  # noqa: E501

        :return: The id of this Item.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Item.

        Identifier of the movie  # noqa: E501

        :param id: The id of this Item.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def data(self) -> str:
        """Gets the data of this Item.

        Data of the item  # noqa: E501

        :return: The data of this Item.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this Item.

        Data of the item  # noqa: E501

        :param data: The data of this Item.
        :type data: str
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
